package com.manuel.delivery.utils

object Constants {
    const val API_URL = "http://192.168.0.13:3000/api/"
    const val PARAM_CLIENT = "CLIENTE"
    const val PARAM_DELIVERY = "REPARTIDOR"
    const val PARAM_RESTAURANT = "RESTAURANTE"
    const val ROUTE_USERS_CREATE = "users/create"
    const val ROUTE_USERS_LOGIN = "users/login"
    const val ROUTE_USERS_UPDATE = "users/update"
    const val ROUTE_USERS_UPDATE_WITHOUT_IMAGE = "users/updateWithoutImage"
    const val ROUTE_CATEGORIES_CREATE = "categories/create"
    const val PROP_ID = "id"
    const val PROP_EMAIL = "email"
    const val PROP_NAME = "name"
    const val PROP_LASTNAME = "lastname"
    const val PROP_PHONE = "phone"
    const val PROP_IMAGE = "image"
    const val PROP_PASSWORD = "password"
    const val PROP_IS_AVAILABLE = "is_available"
    const val PROP_SESSION_TOKEN = "session_token"
    const val PROP_SUCCESS = "success"
    const val PROP_MESSAGE = "message"
    const val PROP_DATA = "data"
    const val PROP_ERROR = "error"
    const val PROP_ROUTE = "route"
    const val PROP_ROLES = "roles"
    const val PROP_USER = "user"
    const val PROP_CATEGORY = "category"
    const val PROP_ROLE = "role"
    const val PROP_IMAGE_CREATE = "image/*"
    const val PROP_TEXT_PLAIN = "text/plain"
    const val PROP_AUTHORIZATION = "Authorization"
}